name: Docker Socket Proxy
description: Home Assistant OS App for a Docker socket proxy
slug: socket-proxy
version: 1.0.1
url: https://github.com/fergus/haos-docker-socket-proxy
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
host_network: true
docker_api: true
full_access: true
protected: false
ports:
  "2375/tcp": 2375
ports_description:
  "2375/tcp": Docker API proxy port
options:
  port: 2375
  ALLOW_START: false
  ALLOW_STOP: false
  ALLOW_RESTARTS: false
  AUTH: false
  BUILD: false
  COMMIT: false
  CONFIGS: false
  CONTAINERS: false
  DISABLE_IPV6: false
  DISTRIBUTION: false
  EVENTS: true
  EXEC: false
  GRPC: false
  IMAGES: false
  INFO: false
  LOG_LEVEL: info
  NETWORKS: false
  NODES: false
  PING: true
  PLUGINS: false
  POST: false
  SECRETS: false
  SERVICES: false
  SESSION: false
  SWARM: false
  SYSTEM: false
  TASKS: false
  VERSION: true
  VOLUMES: false
schema:
  port: port
  ALLOW_START: bool
  ALLOW_STOP: bool
  ALLOW_RESTARTS: bool
  AUTH: bool
  BUILD: bool
  COMMIT: bool
  CONFIGS: bool
  CONTAINERS: bool
  DISABLE_IPV6: bool
  DISTRIBUTION: bool
  EVENTS: bool
  EXEC: bool
  GRPC: bool
  IMAGES: bool
  INFO: bool
  LOG_LEVEL: "list(info|notice|warning|err|debug)"
  NETWORKS: bool
  NODES: bool
  PING: bool
  PLUGINS: bool
  POST: bool
  SECRETS: bool
  SERVICES: bool
  SESSION: bool
  SWARM: bool
  SYSTEM: bool
  TASKS: bool
  VERSION: bool
  VOLUMES: bool
